# Site settings
title: Another blog on coding
email: joe@clanryan.us
description: > # this means to ignore newlines until "baseurl:"
  Another blog about my journey learning new programming languages after a long
  absence.  Although I'm working as a network analyst, I really enjoy writing
  code and learning new languages more.  This follows my journey learning all
  the latest and maybe even revisiting some older languages like C++
baseurl: ""
url: "http://joeryan.github.io" # the base hostname & protocol for your site
twitter_username: iamjoeryan
github_username:  joeryan

# Build settings
markdown: kramdown
